### ISSUE TITLE
Not showing correct connection

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-TaxiService/CommNetConstellation#10]
I got a Mun lander which uses a channel for Mun alone, the only other vessel using this channel is the Mun orbiter.

I set to show all active connections in map view.

The active connection shown is the same the stock readout on top left shows, via a relay sat in Mun orbit directly to Kerbin.

It should show the connection to the orbiter first, then from the orbiter to Kerbin (with relay or not).

**Comment by KSP-TaxiService** [comment]
Ehhh, I am sorry but your report is severely lacking any information required for troubleshooting. I am not seeing any screenshot or what kind of antennas on the lander or orbiter.

If it is still persisting today, please help to provide the screenshot and information above. Otherwise, I will close this later.

**Comment by Gordon-Dry** [comment]
I can do that for you, because I still understand my description.
So I was not drunk as I wrote it.
